[build]
command = "pnpm build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/mixing-mastering"
to = "/mixing-and-mastering"
status = 301
force = true

[[redirects]]
from = "/education"
to = "/project-feedback"
status = 301
force = true

[[redirects]]
from = "/clients-credits"
to = "/clients-and-credits"
status = 301
force = true

[[redirects]]
from = "/post/mixing-tip-subtractive-eq-first-additive-eq-second"
to = "/blog/2022/subtractive-eq-first-additive-eq-second"
status = 301
force = true

[[context.test.headers]]
for = "/*"

[context.test.headers.values]
X-Robots-Tag = "noindex, nofollow"

[[context.test.redirects]]
from = "/robots.txt"
to = "/robots-test.txt"
status = 200
force = true
